### ISSUE TITLE
Unable to run your application

### ISSUE THREAD

**Issue by Deys2000** [kaazii/EECS2311#14]
I have tried both methods in your readme file to run your group project. In the case of running it on eclipse, I receive the following error:
![image](https://user-images.githubusercontent.com/29327897/108807474-90250980-7572-11eb-9668-c72c5637a995.png)

And in the case of downloading the zip file and going through cmd, After the following step below, the cmd line just tells me that the jar file does not exist. 
![image](https://user-images.githubusercontent.com/29327897/108807721-1c373100-7573-11eb-8e52-06642d0756e7.png)

Please let me know if I am the only one facing these issues among other students that are peer assessing your project. If that is the case, then the issue may be personal and I will look further into it.

**Comment by Shogri** [comment]
Just to be completely sure, are you running the cmd inside the unzipped folder?

**Comment by zhouziqi13** [comment]
@Deys2000 
We are actively working on resolving the first issue. There is something wrong with the included Wrapper version. If you can navigate to preferences -> Gradle -> select Gradle version and select 5.8.1 or 5.8. Refresh Gradle again, it should resolve this issue.
For the .jar method, you will need to type in these comments in the same folder TAB2XML_GROUP13. 
Hopefully, you are able to resolve this problem! 
Alternatively, you can download the doris branch instead. This should work fine now. Sorry about the inconvenience.

**Comment by Deys2000** [comment]
@zhoudoris13 
I read the updated readme and downloaded the doris branch. It is working for me, thank you.
![image](https://user-images.githubusercontent.com/29327897/108951892-c4fa9480-7636-11eb-953b-be348699fbf5.png)


@Shogri 
I dont recall if I was inside the unzipped folder. Perhaps I wasnt if I am the only one that this did not work for.

**Comment by zhouziqi13** [comment]
@Deys2000 Glad to hear!
This issue is closed.
