### ISSUE TITLE
Bug: Unable to Translate Bass Text Tab into MusicXML Format

### ISSUE THREAD

**Issue by MaishaRahman98** [kaazii/EECS2311#31]
**ID:** #31 
**Who Raised the Bug:** Maisha Rahman
**Version:** 4371e15
**Title:** Unable to Translate Bass Text Tab into MusicXML Format
**Platform:** Windows 10
**Reproduction Steps:**
How the Bug was found and how to recreate it:
1. Run the application
2. Select the _Bass_ section
3. Click on _Upload a File_ symbol
- Select
[bassTabSimple.txt](https://github.com/kaazii/EECS2311/files/6192920/bassTabSimple.txt)

4. Click on _Translate_
5. Click on _Save_, and save the file
6. Open the saved file

**Expected Outcome:**
A MusicXML file containing the xml code from translating the bass tablature.
**Actual Outcome:**
The MusicXML file contains the bass text tablature, not its xml translation.
Here is a screenshot of this MusicXML file:
![image](https://user-images.githubusercontent.com/77294562/112223234-05324000-8c00-11eb-9a2d-95189d3d3bec.png)

**Priority:**
Please implement to code so that a MusicXML file containing the xml translation of the bass tablature is produced after clicking “Translate” and then “Save”
**Severity:**
High.

**Comment by zhouziqi13** [comment]
@MaishaRahman98 Bass translation is still in development. Thank you for your bug report.

**Comment by zhouziqi13** [comment]
@zhoudoris13 @hargovindsingh Will address this

**Comment by zhouziqi13** [comment]
#31 Resolved, closed.
