### ISSUE TITLE
Bug: Translating Guitar Tablature

### ISSUE THREAD

**Issue by nugea** [kaazii/EECS2311#32]
ID: #32 
**Reporter:** Ali Sheikhi alish(at)my(dot)yorku(dot)ca
**Tilte:** Guitar Tablature Not Translating
**Version:** 4371e15acc3420537022e13b346ae3e43903b583
**Platform:** macOS
**Reproduction:** After opening guitar tablature and clicking on translate, nothing happens. I attached the samples used. The [sample](https://github.com/kaazii/EECS2311#guitar-tablature) provided on readme page seems to be the only functional guitar tablature. 
[guitarTabT.txt](https://github.com/kaazii/EECS2311/files/6193099/guitarTabT.txt)
[guitarTabl.txt](https://github.com/kaazii/EECS2311/files/6193100/guitarTabl.txt)
**Expected:** Window should show the xml output. 
**Actual:**  Nothing happens after clicking on translate. The screenshots were taken after clicking on translate button. 
<img width="700" alt="Screen Shot 2021-03-23 at 6 24 28 PM" src="https://user-images.githubusercontent.com/68204590/112226781-044fdd00-8c05-11eb-92ce-a711dacfdc6e.png">
<img width="698" alt="Screen Shot 2021-03-23 at 6 32 41 PM" src="https://user-images.githubusercontent.com/68204590/112227498-2ac24800-8c06-11eb-863f-18b35e0fa981.png">
**Severity:** Major - Application functionality

**Comment by zhouziqi13** [comment]
@nugea fixed with new release :) Thank you for your feedback
