### ISSUE TITLE
Bug: Bass Tablature Not Translating

### ISSUE THREAD

**Issue by nugea** [kaazii/EECS2311#33]
ID: #33 
**Reporter:** Ali Sheikhi alish(at)my(dot)yorku(dot)ca
**Tilte:** Bass Tablature Not Translating
**Version:** 4371e15acc3420537022e13b346ae3e43903b583
**Platform:** macOS
**Reproduction:** After opening bass tablature and clicking on translate, nothing happens. I attached the samples used. 
[bassTablature.txt](https://github.com/kaazii/EECS2311/files/6193130/bassTablature.txt)
[bassTablatureT.txt](https://github.com/kaazii/EECS2311/files/6193131/bassTablatureT.txt)
**Expected:** Window should show the xml output. 
**Actual:**  Nothing happens after clicking on translate. The screenshot was taken after clicking on translate button. 
<img width="700" alt="Screen Shot 2021-03-23 at 6 36 21 PM" src="https://user-images.githubusercontent.com/68204590/112227969-dd92a600-8c06-11eb-9e7f-dd515f97ca81.png">
**Severity:** Major - Application functionality

**Comment by zhouziqi13** [comment]
@nugea brought up in this issue https://github.com/kaazii/EECS2311/issues/31. Closed
