### ISSUE TITLE
Bug: XML Output for Drum Tab is Incorrect

### ISSUE THREAD

**Issue by MaishaRahman98** [kaazii/EECS2311#34]
**ID:** #34
**Who Raised the Bug:** Maisha Rahman
**Version:** 4371e15
**Title:** XML Output for Drum Tab is Incorrect
**Platform:** Windows 10
**Reproduction Steps:**
How the Bug was found and how to recreate it:
1. Run the application
2. Select the _Drum_ section
3. Click on _Upload a File_ symbol
- Select 
[drumexample.txt](https://github.com/kaazii/EECS2311/files/6193198/drumexample.txt)

4. Click on _Translate_
5. Click on _Save_ and save in MusicXML format
6. Upload the MusicXML file in MusicXML viewer called MuseScore.

**Expected Outcome:**
![image](https://user-images.githubusercontent.com/77294562/112229507-7f1af700-8c09-11eb-8940-7fabc5d3bda8.png)

**Actual Outcome:**
![image](https://user-images.githubusercontent.com/77294562/112229380-40853c80-8c09-11eb-9143-4509c7ee9878.png)

**Priority:**
Please implement translating drum tabs into correct MusicXML files.
**Severity:**
High

**Comment by zhouziqi13** [comment]
@Shogri

**Comment by zhouziqi13** [comment]
@Shogri @zhoudoris13 @yamany-ali-216513269  will address this

**Comment by Shogri** [comment]
Fixed as of 705b14c
