### ISSUE TITLE
Bug: Incorrect Guitar Tablature Output

### ISSUE THREAD

**Issue by nugea** [kaazii/EECS2311#35]
ID: #35 
**Reporter:** Ali Sheikhi alish(at)my(dot)yorku(dot)ca
**Tilte:** Incorrect Guitar Tablature Output 
**Version:** 4371e15acc3420537022e13b346ae3e43903b583
**Platform:** macOS and MuseScore 3
**Reproduction:** Converting the [sample](https://github.com/kaazii/EECS2311#guitar-tablature) provided on readme page, seems to be the only functional guitar tablature. After translation if you click on restart and then translate again in the new output the notes would be repeated. If you repeat this n times then the tablature would be repeated n times in the output. 
<img width="697" alt="Screen Shot 2021-03-23 at 6 50 49 PM" src="https://user-images.githubusercontent.com/68204590/112229081-b210bb00-8c08-11eb-8187-8eab63c1f291.png">
**Expected:** 
<img width="834" alt="Screen Shot 2021-03-23 at 7 00 00 PM" src="https://user-images.githubusercontent.com/68204590/112230236-f69d5600-8c0a-11eb-91ff-f83248d41299.png">
**Actual:**  Some of the notes are wrong. You can see them highlighted above. And is repeated 4 times because I repeated the above process 4 times. 
<img width="869" alt="Screen Shot 2021-03-23 at 6 55 41 PM" src="https://user-images.githubusercontent.com/68204590/112229455-60b4fb80-8c09-11eb-93a8-d9fd463133fa.png">
**Severity:** Major - Guitar Notes needs correction and needs to restart to output correct xml after one translation

**Comment by zhouziqi13** [comment]
@Shogri @kaazii issue to look into

**Comment by zhouziqi13** [comment]
@yamany-ali-216513269

**Comment by Shogri** [comment]
Repeat issue was fixed along with #48 . 
With regards to the incorrect notes, it looks like it's been fixed in a previous commit, as I can't repro.
![image](https://user-images.githubusercontent.com/29787791/113148177-8d67a500-91ff-11eb-90fc-b136194c7d47.png)
![image](https://user-images.githubusercontent.com/29787791/113148227-9ce6ee00-91ff-11eb-9b43-f03ffc15c115.png)
