### ISSUE TITLE
Bug: Auto Instrument Detection is Inaccurate

### ISSUE THREAD

**Issue by MaishaRahman98** [kaazii/EECS2311#36]
**ID:**#36
**Who Raised the Bug:** Maisha Rahman
**Version:** 4371e15
**Title:** Auto Instrument Detection is Inaccurate
**Platform:** Windows 10
**Reproduction Steps:**
How the Bug was found and how to recreate it:
1. Run the application
2. Make sure to checkmark/select _Instrument Detect_ 
3. Click on _Upload a File_ symbol
4. Select 
[guitarTablatureComplex.txt](https://github.com/kaazii/EECS2311/files/6193320/guitarTablatureComplex.txt)
5. Click _Translate_

**Expected Outcome:**
Since guitarTablatureComplex.txt is a guitar tab, the auto detect feature should detect that it is a guitar tab.
**Actual Outcome:**
After uploading the guitarTablatureComplex.txt into the application, the application detects it as a drum tab:
![image](https://user-images.githubusercontent.com/77294562/112231699-978d1080-8c0d-11eb-922f-df4de273535b.png)
**Priority:**
Please implement detection of guitar tabs like guitarTablatureComplex.txt.
**Severity:**
Medium

**Comment by zhouziqi13** [comment]
@MaishaRahman98 Thank you for bringing up the issue. This feature is in development for our next release

**Comment by zhouziqi13** [comment]
@kaazii @hargovindsingh @yamany-ali-216513269 will address this along side with input validation

**Comment by zhouziqi13** [comment]
#36 should work for most cases. If not detected will prompt users for selection. Closed
