### ISSUE TITLE
Bug: Prints out Wrong Translation

### ISSUE THREAD

**Issue by Gaziy-Nabaa-215820095** [kaazii/EECS2311#37]
### **Name:** 
Program outputs wrong translation
### **Description:** 
The program translates a drum tablature as a bass tablature, since the "Bass" option is selected from on the panel.
### **Steps to Produce:**
 Convert a drum tablature while selecting the "Bass" option on the panel.
### **Expected result:**
 Outputs an error message since the tablature does not match the selection 
### **Actual Result:**
 Tablature gets converted as a bass tablature
### **Priority:**
 High
### **Status:**
 Ready for development
### **Screenshot:**
![image](https://user-images.githubusercontent.com/46408225/112233983-dc1aab00-8c11-11eb-9bcb-a2cc0cfdbcd0.png)

**Comment by zhouziqi13** [comment]
@Gaziy-Nabaa-215820095 This issue is mentioned in https://github.com/kaazii/EECS2311/issues/31. Closed.
