### ISSUE TITLE
Bug: Unable to Translate Guitar Tablature

### ISSUE THREAD

**Issue by Gaziy-Nabaa-215820095** [kaazii/EECS2311#38]
### **Name:** 
Program does not translate guitar tablature
### **Description:** 
The program stops responding when a guitar tablature and "Guitar" option is selected.
### **Steps to Produce:**
 Convert a guitar tablature while selecting the "Guitar" option on the panel.
### **Expected result:**
 Xml translation of the selected guitar tablature.
### **Actual Result:**
 Program resets the texts space to an empty space and stops responding 
### **Priority:**
 High
### **Status:**
 Ready for development
### **Screenshot:**
![image](https://user-images.githubusercontent.com/46408225/112237683-8cd87880-8c19-11eb-88d4-4bfc5859c7db.png)

**Comment by zhouziqi13** [comment]
@Gaziy-Nabaa-215820095 Thank you for bringing up this issue. This issue and corresponding feature are mentioned in https://github.com/kaazii/EECS2311/issues/36. Closed
