### ISSUE TITLE
Bug: Unable to Convert Bass Tablature

### ISSUE THREAD

**Issue by Gaziy-Nabaa-215820095** [kaazii/EECS2311#39]
### **Name:** 
Program does not translate long bass tablatures
### **Description:** 
The program stops responding when a long bass tablature is selected.
### **Steps to Produce:**
 Convert a bass tablature with the program
### **Expected result:**
 Xml translation of the selected bass tablature.
### **Actual Result:**
 Program resets the texts space to an empty space and stops responding 
### **Priority:**
 High
### **Status:**
 Ready for development
### **Screenshot:**
Screenshot is taken after clicking the "Translate button"
![image](https://user-images.githubusercontent.com/46408225/112239421-cf4f8480-8c1c-11eb-9a7f-9289413e40df.png)

**Comment by zhouziqi13** [comment]
@Gaziy-Nabaa-215820095 Thank you for bringing up the issue. #31 brings up the same issue. Closed
