### ISSUE TITLE
Bug: Translate guitar issue

### ISSUE THREAD

**Issue by Shawnli3287** [kaazii/EECS2311#40]
Name
Translate guitar tablature issue

Description
The program doesn't translate the guitar tablature. 

Steps to reproduce
Run the main as java application, select the Guitar --> Click upload and upload the guitar tablature --> Click the translate 

Expected result
Correctly translate the tablature to xml

Actual result
After uploading the file and translate it, the textarea becomes empty, doesn't have any XML show up

Priority
high

Status
Ready for development.

Screenshot
![image](https://user-images.githubusercontent.com/46501533/112243594-3a508980-8c24-11eb-931e-2ffc99748e76.png)
![image](https://user-images.githubusercontent.com/46501533/112243649-52c0a400-8c24-11eb-8763-7f0980c4d9d1.png)

**Comment by zhouziqi13** [comment]
@Li-wenxuan-216374324 Thank you for bringing this up. #36 deals with related issues and features. @Shogri @hargovindsingh take a look at this tablature format. Closed.
