### ISSUE TITLE
Bug: Auto detect tablature problem

### ISSUE THREAD

**Issue by Shawnli3287** [kaazii/EECS2311#41]
Name
Auto-detect type of tablature problem

Description
upload the guitar tablature but the program is auto-detect become to drum tablature

Steps to reproduce
Run the main as java application, select the Guitar --> Click upload and upload the guitar tablature, when the cursor move off the Guitar, the program will auto turn translate type to Drum

Expected result
Correctly detect tablature and translate it correctly

Actual result
The program is detect wrong and cannot covert to xml

Priority
high

Status
Ready for development.

Screenshot
![image](https://user-images.githubusercontent.com/46501533/112244726-06766380-8c26-11eb-92bb-6d9d5fe4a8f7.png)
![image](https://user-images.githubusercontent.com/46501533/112244760-15f5ac80-8c26-11eb-9e1c-1154f2dd2d2c.png)
[guitarTablature.txt](https://github.com/kaazii/EECS2311/files/6193895/guitarTablature.txt)

**Comment by zhouziqi13** [comment]
@Li-wenxuan-216374324 Thank you for bringing up this issue. #36 Addresses the same issue. Closed
