### ISSUE TITLE
Bug: Unable to Convert Guitar Tablature

### ISSUE THREAD

**Issue by Hua-Kevin** [kaazii/EECS2311#43]
Reporter: Kevin Hua
Email: kevhua36@my.yorku.ca
Version: 8013aee
Platform: Windows 10

Name:
The application does not translate guitar tablature

Description:
The program is unable to convert guitar tablature under the guitar option.

Steps to Produce:
Import a guitar tablature while under the "Guitar" option on the panel and click translate.

Expected result:
The application converts tablature into XML translation of the tab.

Actual Result:
The application does not freeze, but rather the translate button is blurred and unusable while the tablature is not converted at all. Also in the console, there are a lot of exceptions printed out.

Input Used:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Priority:
High

Status:
Ready for development

Screenshot:
![Long waiting time](https://user-images.githubusercontent.com/42554604/112254029-3cbbdf00-8c36-11eb-8c00-0ae995a38b8d.JPG)

Note:
I realized that you have to go to another instrument and back in order to translate the code. But that would lead to my other issue: https://github.com/kaazii/EECS2311/issues/46

**Comment by zhouziqi13** [comment]
@kevhua36 Thank you for bringing this up. #36 brings up the same issue. Closed.
