### ISSUE TITLE
Bug: No error messages when translating a non-tablature

### ISSUE THREAD

**Issue by ljaypals** [kaazii/EECS2311#44]
**ID:** #44
**Reporter:** Lars Jaylen Palalon email: ljaypals@my.yorku.ca
**Title:** No error messages when translating a non-tablature
**Version:**  [9880fac](https://github.com/kaazii/EECS2311/commit/8013aee6306abd1aaae00ef1794476900ecc1201)
**Platform:** Windows 10
**Reproduction:** After opening the application, trying to translate a bunch of random text that is not a tablature. It does not output any error messages or any indication that says it did not go through.

**Expected Outcome:** An error message stating that the tablature is invalid

**Actual Outcome**
This is what happens when it isn't a tablature
![Screenshot 2021-03-24 002033](https://user-images.githubusercontent.com/77308877/112254391-e8652f00-8c36-11eb-969f-b4fa2d159f6b.png)
![Screenshot 2021-03-24 002052](https://user-images.githubusercontent.com/77308877/112254446-02067680-8c37-11eb-9ddb-cec34f1ba6f1.png)

**Priority:** Please make sure that an error message is outputted when there is an incorrect tablature

**Severity:** High

**Comment by zhouziqi13** [comment]
@ljaypals Validation feature will be included for the next release. Stay tuned. Keeping this for reference.

**Comment by zhouziqi13** [comment]
@yamany-ali-216513269 @hargovindsingh @kaazii will address input validation

**Comment by hargovindsingh** [comment]
@ljaypals We have implemented a feature where the tablature conversion process will not continue if the user inputs an illegal character that does not belong in music tablature.

**(Screenshot) User inputs an illegal character 'Q'**
![Untitled](https://user-images.githubusercontent.com/61370713/113080113-94f16480-9193-11eb-8df2-d15378d9edd2.png)
**(Screenshot) Error message shown to the user**
![Untitled2](https://user-images.githubusercontent.com/61370713/113080117-9589fb00-9193-11eb-8d0d-827c161d0b95.png)
