### ISSUE TITLE
Bug: Can save a non-musicXML text into a musicXML file

### ISSUE THREAD

**Issue by ljaypals** [kaazii/EECS2311#45]
**ID:** #45
**Reporter:** Lars Jaylen Palalon email: ljaypals@my.yorku.ca
**Title:** Can save a non-musicXML text into a musicXML file
**Version:** [9880fac](https://github.com/kaazii/EECS2311/commit/8013aee6306abd1aaae00ef1794476900ecc1201)
**Platform:** Windows 10
**Reproduction:** After opening the application, either a blank or some random input will still allow the program to save it into a musicXML file even though it is not one.

**Expected Outcome:**  An error message stating that the input cannot be saved into a musicXML file

**Actual Outcome:** 
This is what happens when I save a random text even though it isn't a musicXML file
![Screenshot 2021-03-24 003021](https://user-images.githubusercontent.com/77308877/112255356-637b1500-8c38-11eb-82d6-2e2db3ff2a86.png)

**Priority:** Please allow the program to ensure that when it is time to save, it should save the musicXML format only.

**Severity:** Medium

**Comment by zhouziqi13** [comment]
@ljaypals Thank you for bringing up this issue. We are including this as a feature. Will consult product owner.
