### ISSUE TITLE
Bug: Converting non-tablature

### ISSUE THREAD

**Issue by Hua-Kevin** [kaazii/EECS2311#46]
Reporter: Kevin Hua
Email: kevhua36@my.yorku.ca
Version: 8013aee
Platform: Windows 10

Name
Able to convert non-tablature

Description
When the user inputs random text, for example: "asdasdasd", and hit translate. The application would successfully convert it to its XML translation.

Steps to reproduce
Run the application, under its default settings, input the given guitar tablature and translate then type some random characters, and hit translate. Does not report any error but will instead be successfully converted.

Expected result
An error message stating that the tablature is invalid or wipe the text box clean.

Actual result
The application detects nothing and was able to convert to XML.

Priority
high

Status
Ready for development.

Input Used
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

then

asdasdasd

Screenshot
![pic1](https://user-images.githubusercontent.com/42554604/112255426-886f8800-8c38-11eb-9a3d-fff37ec96314.JPG)
![pic2](https://user-images.githubusercontent.com/42554604/112255430-8b6a7880-8c38-11eb-9699-002bba0eaf72.JPG)
![pic3](https://user-images.githubusercontent.com/42554604/112255432-8c030f00-8c38-11eb-8b0d-8adfb02e0045.JPG)

**Comment by zhouziqi13** [comment]
@kevhua36 Thank you for bringing up this issue. #44 brings up the same issue. Closed
