### ISSUE TITLE
Bug: Drum Translation Issue

### ISSUE THREAD

**Issue by Hua-Kevin** [kaazii/EECS2311#47]
Reporter: Kevin Hua
Email: kevhua36@my.yorku.ca
Version: 8013aee
Platform: Windows 10

Name:
The program outputs the wrong translation instead of an error

Description:
The program translates a drum tablature even though the input is incorrect.

Steps to Produce:
Run the application. Input the text shown in the Input Used section (the app will automatically detect that it's drum), then click translate.

Expected result:
Outputs an error message since the tablature is poorly made and incorrect or clear the text box

Actual Result:
Tablature gets converted to the XML translation

Input Used:
CC|x---------------|--------x-------|
HH|--x-x-x-x-x-x-x-|----------------|
SD|----o-------o---|oooo------------ooooooooooo------------|
HT|----------------|----oo-------------------oooooo     ----|
MT|----------------|------oo---xxxx-----|
BD|o-------o-------|o-------o-------|

Priority:
Medium

Status:
Ready for development

Screenshot:
![Picture1](https://user-images.githubusercontent.com/42554604/112256470-3465a300-8c3a-11eb-9c33-8fac372e08a7.JPG)
![Picture2](https://user-images.githubusercontent.com/42554604/112256471-362f6680-8c3a-11eb-9730-2cb549f3c66c.JPG)
![Picture3](https://user-images.githubusercontent.com/42554604/112256472-36c7fd00-8c3a-11eb-9d82-22ecefdcfdf3.JPG)

**Comment by zhouziqi13** [comment]
@kevhua36 #44 addresses the same issue. Thank you for bringing it up. Closed
