### ISSUE TITLE
Bug: Restart not working properly

### ISSUE THREAD

**Issue by ljaypals** [kaazii/EECS2311#48]
**ID:** #48 
**Reporter:** Lars Jaylen Palalon email: ljaypals@my.yorku.ca
**Title:** Restart not working properly
**Version:** [9880fac](https://github.com/kaazii/EECS2311/commit/8013aee6306abd1aaae00ef1794476900ecc1201)
**Platform:** Windows 10
**Reproduction:** 
Sample Guitar Tab used
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
After translating a guitar tab, then reset, then translate again. Both iterations of translating the tab are on the output file. This creates a duplication of the same tab on the same file. It is evident when opening it on museScore

**Expected Outcome:**
![Screenshot 2021-03-24 004809](https://user-images.githubusercontent.com/77308877/112257154-c53c7e80-8c3a-11eb-911a-a9df671123b7.png)

**Actual Outcome:**
This happens when I click reset 3 times and it outputs the tablature 3 times into the output file
![Screenshot 2021-03-24 004858](https://user-images.githubusercontent.com/77308877/112257170-ccfc2300-8c3a-11eb-99a5-b292099c033a.png)

**Priority:** Please make the restart button work where after clicking restart it does not continuously add to the output file after every translate.

**Severity:** Medium

**Comment by zhouziqi13** [comment]
@ljaypals fixed for the new release. Closed
