### ISSUE TITLE
Modifying the time signature of a whole tab throws null pointer and generates corrupt xml

### ISSUE THREAD

**Issue by PBaciu** [kaazii/EECS2311#50]
Reporter: Patrick Alexander Baciu
Email: baciupat@my.yorku.ca
Version: 8013aee
Platform: Windows 10
See #49 
Name:
Modifying time signature of a entire tab throws null pointer exception and generates corrupted output.

Description:
When attempting to change the time signature of the entire tab, a null pointer exception is thrown and the output of the music xml file is corrupted and unreadable.

Steps to Produce:

Start the application.
Paste in this sample guitar tab.
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
Click Translate
Change the dropdown to 3/4
Click confirm (generates null pointer exception) [screenshot 1]
Click save (generates corrupted xml) [screenshot 2 and screenshot3]
Expected result:
Measures 1 and 2 should be in 3/4 time and thus the duration of the chord should change.

Actual Result:
Null pointer exception + corrupted output.

Input Used:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Priority:
Medium

Status:
Ready for development

Screenshots:

![image](https://user-images.githubusercontent.com/77293069/112345057-1714f100-8c9b-11eb-8b12-e943c191f3cf.png)
![image](https://user-images.githubusercontent.com/77293069/112345068-1aa87800-8c9b-11eb-9d2a-66b09b29a02c.png)
![image](https://user-images.githubusercontent.com/77293069/112345097-2005c280-8c9b-11eb-8358-e6e39e512f5b.png)

**Comment by zhouziqi13** [comment]
@PBaciu #49 brings up the same issue. Closed
