### ISSUE TITLE
Bug: Random sentences in the TextArea does not raise errors

### ISSUE THREAD

**Issue by Kumar-Venkatessh-216693764** [kaazii/EECS2311#52]
Reporter: Venkatessh Kumar

Email: venki365@my.yorku.ca

Issue Title: Random sentences in the TextArea does not raise errors.

Version: Tab2MXL March 24 2021 Master

Platform: MacOS Version 10.13.6

Steps to Reproduce:

-Write various sentences on the TextArea
-Click on "Translate"
-Click on "Confirm"
-Check if there are error messages that show up.
-Check the console.

Expected:
Error prompts should be raised when trying to translate an invalid tablature in the TextArea. The User should not be allowed to translate an invalid tablature.

Actual:
After the writing down a random sentence and clicking the Translate button, then clicking on Confirm, we go back to the first page with no information and what has happened. Then when looking at the console, we can see that there has been multiple null-pointer errors raised and the User was not informed about it.

Priority: Medium - This bug needs to be fixed since there are multiple errors being raised in the console. This, although is not a high priority since it does not crash the app.

Severity: Medium- The app does not crash due to this issue, but a lot of errors are raised in the console and the User is unaware of this situation.

Screenshots:

First page when the app is run:
<img width="812" alt="Screen Shot 2021-03-24 at 7 41 25 PM" src="https://user-images.githubusercontent.com/46407886/112345416-721c0780-8cde-11eb-9beb-040cad499694.png">

Input a random sentence in the TextArea:
<img width="812" alt="Screen Shot 2021-03-24 at 7 44 14 PM" src="https://user-images.githubusercontent.com/46407886/112345499-84964100-8cde-11eb-8f36-99516ea4cd08.png">

The Pop-up after hitting the translate button (Should have prompted an error message due to invalid input):
<img width="434" alt="Screen Shot 2021-03-24 at 7 45 26 PM" src="https://user-images.githubusercontent.com/46407886/112345547-92e45d00-8cde-11eb-8ef8-897aec289a82.png">

The app screen after the translation is performed:
<img width="812" alt="Screen Shot 2021-03-24 at 7 46 54 PM" src="https://user-images.githubusercontent.com/46407886/112345670-adb6d180-8cde-11eb-8567-9663295977e7.png">

The errors displayed in the console after this task:
<img width="1033" alt="Screen Shot 2021-03-24 at 7 47 23 PM" src="https://user-images.githubusercontent.com/46407886/112345740-be674780-8cde-11eb-9887-ce36e5d3a54a.png">

**Comment by zhouziqi13** [comment]
@Kumar-Venkatessh-216693764 Thank you for bringing this issue. #44 addresses the same issue. Closed
