### ISSUE TITLE
Modifying tab text does not auto detect instrument change

### ISSUE THREAD

**Issue by PBaciu** [kaazii/EECS2311#53]
Reporter: Patrick Alexander Baciu
Email: baciupat@my.yorku.ca
Version: 8013aee
Platform: Windows 10

Name:
Modifying tab text does not auto detect instrument change.

Description:
When pasting a guitar tab, and modifying it to be a bass tab, the bolded instrument indicator at the top remains as "Guitar".

Steps to Produce:

Start the application.
Paste in this sample guitar tab.
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
(note that the auto detect worked well here)
Edit the guitar tab such that it looks like this (a valid bass tab)
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
(Note that auto detect did not work here)

Expected result:
Auto detect should understand that this is a bass tab and not a guitar tab

Actual Result:
Auto detect still thinks that the input is a guitar tab

Input Used:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Priority:
Low

Status:
Ready for development

Screenshots:
![image](https://user-images.githubusercontent.com/77293069/112346091-0153fb80-8c9c-11eb-8df1-34b2d984dd82.png)
![image](https://user-images.githubusercontent.com/77293069/112346127-0913a000-8c9c-11eb-98a1-2ff622ab30e9.png)

**Comment by zhouziqi13** [comment]
@PBaciu Thank you for bringing up this issue. #41 fix will address this issue. Closed.
