### ISSUE TITLE
Bug: Able to save any text as a musicxml file

### ISSUE THREAD

**Issue by Kumar-Venkatessh-216693764** [kaazii/EECS2311#54]
Reporter: Venkatessh Kumar

Email: venki365@my.yorku.ca

Issue Title: Able to save any text as a musicxml file.

Version: Tab2MXL March 24 2021 Master

Platform: MacOS Version 10.13.6

Steps to Reproduce:

-Drag and Drop/Copy-Paste a valid tablature
-Click on "Save"
-Select "MusicXML"
-Click on "Confirm"
-Specify a file name and save location for the file.
-Click "Save"

Expected:
Error prompts raised when trying to save contents that include only text to a musicxml form.

Actual:
There are no error prompts displayed and the User is allowed to save a text file in the musicxml format. The file will be corrupted if this is not handled.

Priority: Low - This bug is not encountered too often but should still be handled for the ease of use by the User.

Severity: Medium- The app does not crash due to this issue, but the file that is saved will get corrupted and cause the user some issues.

Content of uploaded file:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Screenshots:

First page when the app is run:
<img width="812" alt="Screen Shot 2021-03-24 at 8 26 28 PM" src="https://user-images.githubusercontent.com/46407886/112349088-dee4d100-8ce1-11eb-9bc2-2edff5238714.png">

Upload the file onto the app:
<img width="812" alt="Screen Shot 2021-03-24 at 8 35 44 PM" src="https://user-images.githubusercontent.com/46407886/112349250-0045bd00-8ce2-11eb-9f9f-d0bb17d04911.png">

The pop-up after clicking on save:
<img width="434" alt="Screen Shot 2021-03-24 at 8 35 56 PM" src="https://user-images.githubusercontent.com/46407886/112349301-0c317f00-8ce2-11eb-8f71-31631da751e6.png">

The screen after selecting MusicXML -> Confirm:
<img width="719" alt="Screen Shot 2021-03-24 at 8 36 09 PM" src="https://user-images.githubusercontent.com/46407886/112349383-1ce1f500-8ce2-11eb-966f-f90e3c34a9b6.png">

After selecting a valid location and name for the file to be saved:
<img width="812" alt="Screen Shot 2021-03-24 at 8 35 44 PM" src="https://user-images.githubusercontent.com/46407886/112349466-308d5b80-8ce2-11eb-9ef9-cb53f54930ba.png">

Proof that the file was saved:
<img width="882" alt="Screen Shot 2021-03-24 at 8 37 08 PM" src="https://user-images.githubusercontent.com/46407886/112349515-397e2d00-8ce2-11eb-8e81-b52d11494cf9.png">

**Comment by zhouziqi13** [comment]
@Kumar-Venkatessh-216693764 Thank you for bringing this to our attention. #45 brings up the same issue. We plan to keep this as a feature but will inquire our product owner.
