### ISSUE TITLE
Bug: Not able to translate a valid tablature

### ISSUE THREAD

**Issue by Kumar-Venkatessh-216693764** [kaazii/EECS2311#55]
Reporter: Venkatessh Kumar

Email: venki365@my.yorku.ca

Issue Title: Not able to translate a valid tablature to a MusicXML file

Version: Tab2MXL March 24 2021 Master

Platform: MacOS Version 10.13.6

Steps to Reproduce:

-Drag and Drop/Copy-Paste a valid tablature
-Click on "Translate"
-Click on "Confirm"
-Check if a converted version is displayed

Expected:
A translated version of the inputted tablature is displayed to the User.

Actual:
The conversion does not take place and no MusicXML form is displayed.

Priority: High - This bug needs to be fixed as soon as possible as this issue will be encountered by every User. Not being able to translate a valid tablature is a major priority to be dealt with immediately.

Severity: High- The console gives Null-Pointer exceptions when the above mentioned steps are reproduced. Although the app does not crash, the said way of performing a conversion based on the User Manual does not work.

Content of uploaded file:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Screenshots:

First page when the app is run:
<img width="812" alt="Screen Shot 2021-03-24 at 8 26 28 PM" src="https://user-images.githubusercontent.com/46407886/112351580-74349500-8ce3-11eb-954c-60244f5a8893.png">

Upload the file onto the app:
<img width="812" alt="Screen Shot 2021-03-24 at 8 35 44 PM" src="https://user-images.githubusercontent.com/46407886/112351728-93332700-8ce3-11eb-9e55-0dcb1eae4f4f.png">

After clicking on translate:
<img width="434" alt="Screen Shot 2021-03-24 at 8 58 17 PM" src="https://user-images.githubusercontent.com/46407886/112352003-d68d9580-8ce3-11eb-8976-cc3cf596d2ec.png">

After clicking on confirm (Stuck on this page):
<img width="812" alt="Screen Shot 2021-03-24 at 8 58 27 PM" src="https://user-images.githubusercontent.com/46407886/112352073-e60cde80-8ce3-11eb-9f3e-c6864ced9751.png">

Screenshots of errors on console:
<img width="1054" alt="Screen Shot 2021-03-24 at 9 01 24 PM" src="https://user-images.githubusercontent.com/46407886/112352523-46038500-8ce4-11eb-965d-4784482ca825.png">

<img width="1037" alt="Screen Shot 2021-03-24 at 8 59 07 PM" src="https://user-images.githubusercontent.com/46407886/112352148-f624be00-8ce3-11eb-8dff-f0a67acd0e6f.png">

**Comment by zhouziqi13** [comment]
@Kumar-Venkatessh-216693764 Thank you for bringing this up to our attention. #41 fix will address this problem. Closed.
