### ISSUE TITLE
Bug: Random words are able to convert

### ISSUE THREAD

**Issue by Saniac249** [kaazii/EECS2311#56]
**Issue Title:** Program allows conversion of random input

After opening the program, if the user types random words in the text field, they are able to convert it to musixXML.

**Version:**

Version 15 of Java SE Platform (* Java-15 as stated in User Manual)

**Platform:**

macOS Big Sur

**Steps to Reproduce:**

- Run the Program
- In the text field enter any words (Screenshot 1)
- The program allows you to convert
- Converts it into a hard coded tablature (Screenshot 2)

**Expected:**

The expectation from the program would be to display an error telling the user that the input is incorrect and suggest changes.

**Actual:**

The program allows the user to convert random words to xml and generates a hard coded xml file.

**Priority:**

High - This is a major bug and might require deeper inspection of the parser. If it allows wrong input then that is a major problem

**Severity:**

High - It confuses the user by taking in wrong input and not generating an error message.

**Screenshots:**

Screenshot 1: Shows the text field with a random word

<img width="695" alt="Screen Shot 2021-03-25 at 6 36 53 AM" src="https://user-images.githubusercontent.com/75386358/112411886-0ade7180-8d37-11eb-89fd-b11a20802b94.png">

Screenshot 2: Shows the random word being converted into a xml file

<img width="696" alt="Screen Shot 2021-03-25 at 6 37 34 AM" src="https://user-images.githubusercontent.com/75386358/112411906-103bbc00-8d37-11eb-9110-20380b2b4a61.png">

**Comment by zhouziqi13** [comment]
@Saniac249 Thank you for bringing this up. #44 deals with the same issue. Closed.
