### ISSUE TITLE
Bug: Instrument Detection detects instruments for random words 

### ISSUE THREAD

**Issue by Saniac249** [kaazii/EECS2311#57]
**Issue Title:** Program's instrument detection detects instruments when random words are inputted 

After opening the program, if the user types random words in the text field and uses the instrument detection, it detects instruments for the wrong input

**Version:**

Version 15 of Java SE Platform (* Java-15 as stated in User Manual)

**Platform:**

macOS Big Sur

**Steps to Reproduce:**

- Run the Program
- In the text field enter any words (Screenshot 1)
- Check the "Instrument Detect" box
- The program detects instruments for random words, in this case Bass (Screenshot2)

**Expected:**

The expectation from the program would be to display an error telling the user that the input is incorrect and no instrument was detected for the input.

**Actual:**

The program's instrument detection detects instrument for false input.

**Priority:**

Medium - This is a mediocre bug which should not require deep inspection but might require test cases to check right or wrong inputs.

**Severity:**

Medium - It is more of a user-experience bug and causes confusion by showing false instrument for the random input which should not be allowed in the first place.

**Screenshots:**

**Screenshot 1:** Shows the text field with a random word

<img width="694" alt="Screen Shot 2021-03-25 at 7 01 52 AM" src="https://user-images.githubusercontent.com/75386358/112412906-b5a35f80-8d38-11eb-9db1-c61c94859ce1.png">

**Screenshot 2:** Shows the instrument detection detecting Bass for the random input

<img width="693" alt="Screen Shot 2021-03-25 at 6 58 58 AM" src="https://user-images.githubusercontent.com/75386358/112412930-c18f2180-8d38-11eb-99a2-ef4b3e83f8e1.png">

**Comment by zhouziqi13** [comment]
@Saniac249 Thank you for bringing this up. #36 deals with the same issue. Closed.
