### ISSUE TITLE
Bug: Resizing Issue

### ISSUE THREAD

**Issue by Saniac249** [kaazii/EECS2311#58]
**Issue Title:** Program resizing needs to be fixed

After opening the program, if the user tries to enter the full screen, the GUI moves to the top left instead of spreading out equally all over the screen or being capped at a certain height/width.

**Version:**

Version 15 of Java SE Platform (* Java-15 as stated in User Manual)

**Platform:**

macOS Big Sur

**Steps to Reproduce:**

- Run the Program
- Click the fullscreen option found on any OS.
- The window moves to the top left of the screen.

**Expected:**

The expectation from the program would be to either display the interface equally all over the full screen or the interface being capped at a certain height or width.

**Actual:**

The program allows user to go to fullscreen but the format moves to the top left.

**Priority:**

Low - This is a minor bug which should not require deep inspection but might require editing to the interface to meet user's expectations either fullscreen or not.

**Severity:**

Low - It is more of a user-experience bug and will make the program more intuitive when fixed.

**Screenshots:**

**Screenshot 1:** Shows the interface in its normal Aspect ratio

<img width="696" alt="Screen Shot 2021-03-25 at 7 12 35 AM" src="https://user-images.githubusercontent.com/75386358/112413771-344ccc80-8d3a-11eb-84ed-ae1df5c93361.png">

**Screenshot 2:** Shows the interface in full screen

<img width="1440" alt="Screen Shot 2021-03-25 at 7 12 43 AM" src="https://user-images.githubusercontent.com/75386358/112413784-37e05380-8d3a-11eb-9432-c8878a8bc213.png">

**Comment by zhouziqi13** [comment]
@Saniac249 Thank you for bringing this up. Currently, the team considers this a good-to-have. We Will revisit if we have the opportunity. Keeping this for the future.

**Comment by zhouziqi13** [comment]
#58. All windows non-resizable. Closed.
